server.port=${PORT:8081}
spring.application.name=common-service

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://Vercel-Admin-ChaturbujaPlots:QsDNB4d3fwNt4wV2@chaturbujaplots.np9kef5.mongodb.net/anjana_common?retryWrites=true&w=majority}
spring.data.mongodb.database=anjana_common

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
app.storage.base-dir=${STORAGE_DIR:./uploads}
app.storage.base-url=${STORAGE_BASE_URL:http://localhost:8081/api/v1/media/files}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,https://chaturbhujaplots-salestool-fe-customer-production.up.railway.app}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
